services:
  - type: web
    name: portfolio-project
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_uye1KBAJk2jR@ep-ancient-haze-a1rcom9x-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
